// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duuplufbkzynrhmtshlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dXBsdWZia3p5bnJobXRzaGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzgwMzYsImV4cCI6MjA2OTI1NDAzNn0.cLrIyi_cyTrRfFdGcRR_TVxg8TknIIqQb5TmXPpDnOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});